name: Integration

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Node 12 sample
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run install
      - run: npm run test
      - run: npm run build

      - name: publish in mpm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
